from datetime import datetime

class textFileHandler:
	def __init__(self, filename):
		self.filename = filename
		
		#Automatically save date and time
		now = datetime.now()
		timestamp = now.strftime("%Y-%m-%d %H:%M:%S")
		with open(self.filename, 'w') as file:
			file.write(f"#Data Generated by Afry's BSDF imaging solution\n#{timestamp} \nSource Measured\nSymmetry PlaneSymmetrical \nSpectralContent Monochrome\nScatterType")
		
	def write_text(self, text):
		with open(self.filename, 'a') as file:
			file.write(text + '\n')
			
	def write_text_position(self, line_number, text):
		lines = []
		with open(self.filename, 'r') as file:
			lines = file.readlines()
			
			if 0 < line_number <= len(lines):			
				lines[line_number] = text + '\n'		
			
			else:
				self.write_text(text)
		
		with open(self.filename, 'w') as file:
			file.writelines(lines)
			
			
